export default {
  seller: ['SINABUDDY MINERAL CO., LIMITED', 'ZHENGZHOU SINABUDDY MINERAL CO.. LTD', ''],
  sellerAddress: [
    `UNIT A&B, 15/F, NEICH TOWER, 128 GLOUCESTER ROAD WANCHAI, HONGKONG.`,
    `NO.27 INNER RING RD, ZHENGDONG NEW DISTRICT, ZHENGZHOU, CHINA`,
    ''
  ],
  bank: [
    `COMPANY NAME: SINABUDDY MINERAL CO., LIMITED
BANK NAME: HSBC HONGKONG
BANK ADDRESS: HEAD OFFICE 1 QUEEN'S ROAD CENTRAL HONG KONG
BANK BIC: HSBCHKHHHKH
ACCOUNT NO: 801332461838`,
    `COMPANY NAME:ZHENGZHOU SINABUDDY MINERAL CO., LTD
BANK NAME: SHANGHAI PUDONG DEVELOPMENT BANK ZHENGZHOU BRANCH
ACCOUNT NO.: 76201457410001173
SWIFT BIC: SPDBCNSH090`,
    ''
  ],
  payment: [
    `20% BY T.T IN ADVANCE AND BALANCE 80% BY T.T AGAINST B/L COPY IN 30 DAYS FROM B/L DATE. ANY PAYMENT THAT ARE NOT PAID WHEN DUE, THE BUYER AGREE TO PAY INTEREST CHARGES AT THE RATE OF 1.5% PER MONTH.`,
    `BY  D/A 45 DAYS AFTER B/L DATE AND "PROTEST" ALLOWED.`,
    `BY D/A 60 DAYS FROM THE BILL OF LADING DATE.`,
    `L/C`,
    ''
  ],
  Terms: [
    `THIS CONTRACT IS MADE BY AND AGREED BETWEEN THE SELLER AND BUYER, IN ACCORDANCE WITH THE TERMS AND CONDITIONS STIPULATED BELOW:`,
    `1.SPECIFICATION, QUANTITY AND PRICE:`,
    `2.INSURANCE: INVOICE VALUE PLUS 10% COVERING ALL RISKS TO BE COVERED BY THE SELLER. `,
    `3.PACKING: `,
    `4.MARKS: SELLER’S PACKING.THE MARKS WITHOUT “MADE IN CHINA” OR SPECIAL MARKS SHOWED ON PACKAGE AS THE BUYER'S REQUEST, THE BUYER SHALL BE LIABLE FOR ALL THE CONSEQUENCE AND EXPENSES IF ANY.`,
    `5.PORT OF LOADING: `,
    `6.PORT OF DESTINATION: `,
    `7.TERMS OF PAYMENT: `,
    `8.DELIVERY TIME: IN ABOUT 30 WORKING DAYS AFTER THE SIGNED SALES CONTRACT.`,
    `9.MORE OR LESS CLAUSE: 2% MORE OR LESS OF LOADING QUANTITY IS ALLOWED.`,
    `10.IF THE FLUCTUATION OF SEA FREIGHT IS ABOVE 30% BETWEEN THE CONTRACT DATE AND THE DELIVERY DATE, THE FREIGHT COST SHOULD BE SETTLED THROUGH NEGOTIATION.`,
    `11.SHIPPING DOCS: THE REQUESTED CUSTOM CLEARANCE DOCS SHOULD BE INFORMED BEFORE THE SHIPMENT. IF BUYER PROPOSE TO MODIFY OR REQUEST ADDITATIONAL DOCS AFTER THE SHIPMENT, THE ADDITIONAL COSTS AND RESPONSIBILITY SHALL BE BORNE BY THE BUYER. THE SHIPPING DOCUMENTS SHALL NOT BE SENT OUT DUE TO THE DELAY PAYMENT FROM THE BUYER,  THE BUYER SHALL BE LIABLE FOR ALL THE CONSEQUENCE AND EXPENSES IF ANY.`,
    `12.FORCE MAJEURE: THE DELAYS OF DELIVERY OR NON-DELIVERY CAUSED BY THE FORCE MAJEURE OCCURRED DURING  PRODUCTION OR SHIPMENT TRANSSHIPMENT PROCESS (INCLUDING WAR, SERIOUS FIRE, FLOOD, TYPHOON, EARTHQUAKE, STRIKES, WEATHER CONDITION, ENVIRONMENTAL PROTECTION CONDITION, GOVERNMENTAL ACTION AND THE OTHER INDIRECT THIRD PARTY EFFECT), THE SELLERS ARE NOT RESPONSIBLE FOR THE DELAYS OR NON-DELIVERY IN THE EVENT OF FORCE MAJEURE AND ANY CONTIGENCIES BEYOND THE SELLERS’ CONTROL. THE SELLER SHALL HAVE THE ADDITIONAL TIME NEEDED TO COMPLETE THE ORDER AND /OR THE RIGHT TO ALLOCATE THE AVAILABLE SUPPLY IN ANY MANNER IF SELECTS.`,
    `13.CLAIM: CLAIMS FOR DAMAGE,  QUANTITY AND QUALITY ISSUES SHOULD BE FILED BY THE BUYERS WITH THE SELLERS WITHIN 21 DAYS AFTER THE ARRIVAL OF THE GOODS AT DESTINATION PORT OR PLACE SUBJECT TO ITEM 6, AND SUPPORTED BY SUFFICIENT EVIDENCE FOR SELLERS REFERENCE. OTHERWISE, SUCH CLAIMS SHALL BE DEEMED WAIVED. ANY SHIPPING COSTS RELATED TO ANY APPROVED EXCHANGE OR REPLACEMENT OF PRODUCTS WILL BE AT THE EXPENSE OF THE BUYER.`,
    `14.ARBITRATION: ALL DISPUTES ARISING FROM THE EXECUTION OF OR IN CONNECTION WITH THIS CONTRACT, SHALL BE SETTLED AMICABLY THROUGH FRIENDLY NEGOTIATION. IN CASE NO SETTLEMENT CAN BE REACHED THROUGH NEGOTIATION, THE CASE SHALL THEN BE SUBMITTED TO CHINA INTERNATIONAL ECONOMIC AND TRADE ARBITRATION COMMISSION (CIETAC) IN ACCORDANCE WITH ITS PROVISIONAL RULES OF PROCEDURE. THE ARBITRAL AWARD IS FINAL AND BINDING UPON BOTH PARTIES. THE ARBITRATION FEES SHALL BE BORNE BY THE LOSING PARTY.`,
    `SIGNED BY THE SELLER `,
    `SIGNED BY THE BUYER`,
  ]
}
